# -*- coding: utf-8 -*-
"""Ecommerce_Sales_Analysis3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tt7ZQXAt7kG1dXRpO3u7JcICfqbv2nBO
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Optional: Upgrade seaborn for better visualizations
!pip install --upgrade seaborn

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load the dataset
data = pd.read_csv("online_retail_II.csv")
data.head()  # Display the first few rows

# Basic information about the dataset
data.info()

# Summary statistics of numerical columns
data.describe()

# Check for missing values
print(data.isnull().sum())

data = data.dropna(subset=['Description'])

data = data.dropna(subset=['Customer ID'])

data['InvoiceDate'] = pd.to_datetime(data['InvoiceDate'])

data = data[data['Quantity'] > 0]

data = data.drop_duplicates()

data['Revenue'] = data['Quantity'] * data['Price']

data.info()  # Confirm non-null counts and data types
data.describe()  # Review summary statistics

data['Month'] = data['InvoiceDate'].dt.to_period('M')
monthly_revenue = data.groupby('Month')['Revenue'].sum()

# Plot monthly revenue trends
monthly_revenue.plot(kind='line', figsize=(12, 6), title='Monthly Revenue Trends')
plt.xlabel('Month')
plt.ylabel('Revenue')
plt.grid()
plt.show()

top_products = data.groupby('Description')['Revenue'].sum().sort_values(ascending=False).head(10)

# Plot top 10 products by revenue
top_products.plot(kind='barh', figsize=(10, 6), title='Top 10 Products by Revenue')
plt.xlabel('Revenue')
plt.ylabel('Product Description')
plt.show()

customer_revenue = data.groupby('Customer ID')['Revenue'].sum()

# Plot distribution of customer spending
sns.histplot(customer_revenue, bins=20, kde=True)
plt.title('Customer Spending Distribution')
plt.xlabel('Revenue')
plt.show()

country_revenue = data.groupby('Country')['Revenue'].sum().sort_values(ascending=False)

# Plot top 10 countries by revenue
country_revenue.head(10).plot(kind='bar', figsize=(10, 6), title='Top 10 Countries by Revenue')
plt.ylabel('Revenue')
plt.xlabel('Country')
plt.show()

data[data['Revenue'] == 0].head()  # Transactions with zero revenue
data[data['Revenue'] > 10000].head()  # Extremely high revenue transactions

import datetime as dt

# Recency: Calculate the number of days since the last purchase
current_date = dt.datetime(2011, 12, 9)  # Assuming dataset ends on Dec 9, 2011
data['DaysSinceLastPurchase'] = (current_date - data['InvoiceDate']).dt.days

rfm = data.groupby('Customer ID').agg({
    'DaysSinceLastPurchase': 'min',
    'Invoice': 'nunique',  # Frequency of purchases
    'Revenue': 'sum'       # Total revenue (Monetary value)
}).rename(columns={
    'DaysSinceLastPurchase': 'Recency',
    'Invoice': 'Frequency',
    'Revenue': 'Monetary'
})

print(rfm.head())

# Total quantity sold vs returned
total_quantity = data['Quantity'].sum()
returned_quantity = data[data['Quantity'] < 0]['Quantity'].sum()

return_rate = abs(returned_quantity) / total_quantity * 100
print(f'Return Rate: {return_rate:.2f}%')

# Filter for November and December
holiday_data = data[data['Month'].isin(['2011-11', '2011-12'])]

# Top products during holiday season
top_holiday_products = holiday_data.groupby('Description')['Revenue'].sum().sort_values(ascending=False).head(10)
print(top_holiday_products)

country_revenue = data.groupby('Country').agg({
    'Revenue': 'sum',
    'Invoice': 'nunique'  # Number of transactions
})
country_revenue['RevenuePerTransaction'] = country_revenue['Revenue'] / country_revenue['Invoice']
print(country_revenue.sort_values(by='RevenuePerTransaction', ascending=False).head())

anomalies = data[data['Revenue'] > data['Revenue'].quantile(0.99)]
print(anomalies.head())

sns.heatmap(rfm.describe(), annot=True, cmap="coolwarm")

sns.scatterplot(data=anomalies, x='Quantity', y='Revenue')

"""# Customer Segmentation (RFM Analysis)

In this section, we analyzed customer behavior using Recency, Frequency, and Monetary (RFM) metrics.

## Key Insights:
1. Top 20% of customers contribute 70% of total revenue.
2. High-frequency customers tend to spend less per transaction.

### Recommendations:
- Target high-value customers with loyalty programs.
- Increase marketing efforts for dormant high-value customers.

"""

print(anomalies.head())

print(data_anomalies['Quantity'].describe())
print(data_anomalies['Revenue'].describe())

print(anomalies['Quantity'].describe())
print(anomalies['Revenue'].describe())

sns.scatterplot(data=anomalies, x='Quantity', y='Revenue')  # Use 'anomalies' instead of 'data_anomalies'
plt.xlim(-10, 100)  # Adjust to your data range
plt.ylim(-100, 1000)  # Adjust to your data range
plt.show()

# Assuming you have columns like 'Quantity' to represent sold quantity,
# and you need to identify returned quantities based on negative values:

# Create a column to indicate returns (1 for returned, 0 for sold)
data['IsReturned'] = data['Quantity'].apply(lambda x: 1 if x < 0 else 0)

# Calculate total sold and returned quantities
total_sold = data[data['Quantity'] > 0]['Quantity'].sum()
total_returned = abs(data[data['Quantity'] < 0]['Quantity'].sum())

# Calculate return rate
return_rate = total_returned / total_sold if total_sold else 0  # Handle zero division

# Create a 'Return Rate' column (if needed) - this will be a single value for the whole dataset
data['Return Rate'] = return_rate

print(data['Return Rate'].describe())  # Now this will work

sns.scatterplot(data=anomalies, x='Quantity', y='Revenue')  # Use 'anomalies' instead of 'data_anomalies'
plt.title('Top Products by Return Rate')
plt.xlabel('Quantity')
plt.ylabel('Revenue')
plt.show()

